#include "instructions.h"

// Instructions based on https://izik1.github.io/gbops/

const Instruction instructions[0x100] = {
    // NOP
    [0x00] = {{.end = true}},

    [0x01] = {{.undefined = true}},
    [0x02] = {{.undefined = true}},
    [0x03] = {{.undefined = true}},

    // INC B
    [0x04] = {{.lhs = B, .uop = INC, .ld = B, .end = true}},

    // DEC B
    [0x05] = {{.lhs = B, .uop = DEC, .ld = B, .end = true}},

    // LD B,u8
    [0x06] = {{0}, {.io = READ_PC, .ld = B, .end = true}},

    [0x07] = {{.undefined = true}},
    [0x08] = {{.undefined = true}},
    [0x09] = {{.undefined = true}},
    [0x0A] = {{.undefined = true}},
    [0x0B] = {{.undefined = true}},
    [0x0C] = {{.undefined = true}},
    [0x0D] = {{.undefined = true}},
    [0x0E] = {{.undefined = true}},
    [0x0F] = {{.undefined = true}},
    [0x10] = {{.undefined = true}},
    [0x11] = {{.undefined = true}},
    [0x12] = {{.undefined = true}},
    [0x13] = {{.undefined = true}},
    [0x14] = {{.undefined = true}},
    [0x15] = {{.undefined = true}},
    [0x16] = {{.undefined = true}},
    [0x17] = {{.undefined = true}},
    [0x18] = {{.undefined = true}},
    [0x19] = {{.undefined = true}},
    [0x1A] = {{.undefined = true}},
    [0x1B] = {{.undefined = true}},
    [0x1C] = {{.undefined = true}},
    [0x1D] = {{.undefined = true}},
    [0x1E] = {{.undefined = true}},
    [0x1F] = {{.undefined = true}},
    [0x20] = {{.undefined = true}},
    [0x21] = {{.undefined = true}},
    [0x22] = {{.undefined = true}},
    [0x23] = {{.undefined = true}},
    [0x24] = {{.undefined = true}},
    [0x25] = {{.undefined = true}},

    // LD H,u8
    [0x26] = {{0}, {.io = READ_PC, .ld = H, .end = true}},

    [0x27] = {{.undefined = true}},
    [0x28] = {{.undefined = true}},
    [0x29] = {{.undefined = true}},
    [0x2A] = {{.undefined = true}},
    [0x2B] = {{.undefined = true}},
    [0x2C] = {{.undefined = true}},
    [0x2D] = {{.undefined = true}},

    // LD L,u8
    [0x2E] = {{0}, {.io = READ_PC, .ld = L, .end = true}},

    [0x2F] = {{.undefined = true}},
    [0x30] = {{.undefined = true}},
    [0x31] = {{.undefined = true}},
    [0x32] = {{.undefined = true}},
    [0x33] = {{.undefined = true}},
    [0x34] = {{.undefined = true}},
    [0x35] = {{.undefined = true}},
    [0x36] = {{.undefined = true}},
    [0x37] = {{.undefined = true}},
    [0x38] = {{.undefined = true}},
    [0x39] = {{.undefined = true}},
    [0x3A] = {{.undefined = true}},
    [0x3B] = {{.undefined = true}},
    [0x3C] = {{.undefined = true}},
    [0x3D] = {{.undefined = true}},

    // LD A,u8
    [0x3E] = {{0}, {.io = READ_PC, .ld = A, .end = true}},

    [0x3F] = {{.undefined = true}},
    [0x40] = {{.undefined = true}},
    [0x41] = {{.undefined = true}},
    [0x42] = {{.undefined = true}},
    [0x43] = {{.undefined = true}},
    [0x44] = {{.undefined = true}},
    [0x45] = {{.undefined = true}},
    [0x46] = {{.undefined = true}},
    [0x47] = {{.undefined = true}},
    [0x48] = {{.undefined = true}},
    [0x49] = {{.undefined = true}},
    [0x4A] = {{.undefined = true}},
    [0x4B] = {{.undefined = true}},
    [0x4C] = {{.undefined = true}},
    [0x4D] = {{.undefined = true}},
    [0x4E] = {{.undefined = true}},
    [0x4F] = {{.undefined = true}},
    [0x50] = {{.undefined = true}},
    [0x51] = {{.undefined = true}},
    [0x52] = {{.undefined = true}},
    [0x53] = {{.undefined = true}},
    [0x54] = {{.undefined = true}},
    [0x55] = {{.undefined = true}},
    [0x56] = {{.undefined = true}},
    [0x57] = {{.undefined = true}},
    [0x58] = {{.undefined = true}},
    [0x59] = {{.undefined = true}},
    [0x5A] = {{.undefined = true}},
    [0x5B] = {{.undefined = true}},
    [0x5C] = {{.undefined = true}},
    [0x5D] = {{.undefined = true}},
    [0x5E] = {{.undefined = true}},
    [0x5F] = {{.undefined = true}},
    [0x60] = {{.undefined = true}},
    [0x61] = {{.undefined = true}},
    [0x62] = {{.undefined = true}},
    [0x63] = {{.undefined = true}},
    [0x64] = {{.undefined = true}},
    [0x65] = {{.undefined = true}},
    [0x66] = {{.undefined = true}},
    [0x67] = {{.undefined = true}},
    [0x68] = {{.undefined = true}},
    [0x69] = {{.undefined = true}},
    [0x6A] = {{.undefined = true}},
    [0x6B] = {{.undefined = true}},
    [0x6C] = {{.undefined = true}},
    [0x6D] = {{.undefined = true}},
    [0x6E] = {{.undefined = true}},
    [0x6F] = {{.undefined = true}},
    [0x70] = {{.undefined = true}},
    [0x71] = {{.undefined = true}},
    [0x72] = {{.undefined = true}},
    [0x73] = {{.undefined = true}},
    [0x74] = {{.undefined = true}},
    [0x75] = {{.undefined = true}},

    // HALT
    [0x76] = {{.halt = true, .end = true}},

    // LD (HL),A
    [0x77] = {{0}, {.lhs = A, .uop = LD_BUS_LHS, .io = WRITE_HL, .end = true}},

    [0x78] = {{.undefined = true}},
    [0x79] = {{.undefined = true}},
    [0x7A] = {{.undefined = true}},
    [0x7B] = {{.undefined = true}},
    [0x7C] = {{.undefined = true}},
    [0x7D] = {{.undefined = true}},
    [0x7E] = {{.undefined = true}},
    [0x7F] = {{.undefined = true}},
    [0x80] = {{.undefined = true}},
    [0x81] = {{.undefined = true}},
    [0x82] = {{.undefined = true}},
    [0x83] = {{.undefined = true}},
    [0x84] = {{.undefined = true}},
    [0x85] = {{.undefined = true}},
    [0x86] = {{.undefined = true}},
    [0x87] = {{.undefined = true}},
    [0x88] = {{.undefined = true}},
    [0x89] = {{.undefined = true}},
    [0x8A] = {{.undefined = true}},
    [0x8B] = {{.undefined = true}},
    [0x8C] = {{.undefined = true}},
    [0x8D] = {{.undefined = true}},
    [0x8E] = {{.undefined = true}},
    [0x8F] = {{.undefined = true}},
    [0x90] = {{.undefined = true}},
    [0x91] = {{.undefined = true}},
    [0x92] = {{.undefined = true}},
    [0x93] = {{.undefined = true}},
    [0x94] = {{.undefined = true}},
    [0x95] = {{.undefined = true}},
    [0x96] = {{.undefined = true}},
    [0x97] = {{.undefined = true}},
    [0x98] = {{.undefined = true}},
    [0x99] = {{.undefined = true}},
    [0x9A] = {{.undefined = true}},
    [0x9B] = {{.undefined = true}},
    [0x9C] = {{.undefined = true}},
    [0x9D] = {{.undefined = true}},
    [0x9E] = {{.undefined = true}},
    [0x9F] = {{.undefined = true}},
    [0xA0] = {{.undefined = true}},
    [0xA1] = {{.undefined = true}},
    [0xA2] = {{.undefined = true}},
    [0xA3] = {{.undefined = true}},
    [0xA4] = {{.undefined = true}},
    [0xA5] = {{.undefined = true}},
    [0xA6] = {{.undefined = true}},
    [0xA7] = {{.undefined = true}},

    // XOR A,B
    [0xA8] = {{.lhs = A, .rhs = B, .uop = XOR, .ld = A, .end = true}},

    [0xA9] = {{.undefined = true}},
    [0xAA] = {{.undefined = true}},
    [0xAB] = {{.undefined = true}},
    [0xAC] = {{.undefined = true}},
    [0xAD] = {{.undefined = true}},
    [0xAE] = {{.undefined = true}},

    // XOR A,A
    [0xAF] = {{.lhs = A, .rhs = A, .uop = XOR, .ld = A, .end = true}},

    [0xB0] = {{.undefined = true}},
    [0xB1] = {{.undefined = true}},
    [0xB2] = {{.undefined = true}},
    [0xB3] = {{.undefined = true}},
    [0xB4] = {{.undefined = true}},
    [0xB5] = {{.undefined = true}},
    [0xB6] = {{.undefined = true}},
    [0xB7] = {{.undefined = true}},
    [0xB8] = {{.undefined = true}},
    [0xB9] = {{.undefined = true}},
    [0xBA] = {{.undefined = true}},
    [0xBB] = {{.undefined = true}},
    [0xBC] = {{.undefined = true}},
    [0xBD] = {{.undefined = true}},
    [0xBE] = {{.undefined = true}},
    [0xBF] = {{.undefined = true}},
    [0xC0] = {{.undefined = true}},
    [0xC1] = {{.undefined = true}},
    [0xC2] = {{.undefined = true}},

    // JP u16
    [0xC3] = {{0},
              {.io = READ_PC, .ld = TMP_LO},
              {.io = READ_PC, .ld = TMP_HI},
              {.uop = LD_PC_TMP, .end = true}},

    [0xC4] = {{.undefined = true}},
    [0xC5] = {{.undefined = true}},
    [0xC6] = {{.undefined = true}},
    [0xC7] = {{.undefined = true}},
    [0xC8] = {{.undefined = true}},
    [0xC9] = {{.undefined = true}},
    [0xCA] = {{.undefined = true}},
    [0xCB] = {{.undefined = true}},
    [0xCC] = {{.undefined = true}},
    [0xCD] = {{.undefined = true}},
    [0xCE] = {{.undefined = true}},
    [0xCF] = {{.undefined = true}},
    [0xD0] = {{.undefined = true}},
    [0xD1] = {{.undefined = true}},
    [0xD2] = {{.undefined = true}},
    [0xD3] = {{.undefined = true}},
    [0xD4] = {{.undefined = true}},
    [0xD5] = {{.undefined = true}},
    [0xD6] = {{.undefined = true}},
    [0xD7] = {{.undefined = true}},
    [0xD8] = {{.undefined = true}},
    [0xD9] = {{.undefined = true}},
    [0xDA] = {{.undefined = true}},
    [0xDB] = {{.undefined = true}},
    [0xDC] = {{.undefined = true}},
    [0xDD] = {{.undefined = true}},
    [0xDE] = {{.undefined = true}},
    [0xDF] = {{.undefined = true}},
    [0xE0] = {{.undefined = true}},
    [0xE1] = {{.undefined = true}},
    [0xE2] = {{.undefined = true}},
    [0xE3] = {{.undefined = true}},
    [0xE4] = {{.undefined = true}},
    [0xE5] = {{.undefined = true}},
    [0xE6] = {{.undefined = true}},
    [0xE7] = {{.undefined = true}},
    [0xE8] = {{.undefined = true}},
    [0xE9] = {{.undefined = true}},
    [0xEA] = {{.undefined = true}},
    [0xEB] = {{.undefined = true}},
    [0xEC] = {{.undefined = true}},
    [0xED] = {{.undefined = true}},
    [0xEE] = {{.undefined = true}},
    [0xEF] = {{.undefined = true}},
    [0xF0] = {{.undefined = true}},
    [0xF1] = {{.undefined = true}},
    [0xF2] = {{.undefined = true}},
    [0xF3] = {{.undefined = true}},
    [0xF4] = {{.undefined = true}},
    [0xF5] = {{.undefined = true}},
    [0xF6] = {{.undefined = true}},
    [0xF7] = {{.undefined = true}},
    [0xF8] = {{.undefined = true}},
    [0xF9] = {{.undefined = true}},
    [0xFA] = {{.undefined = true}},
    [0xFB] = {{.undefined = true}},
    [0xFC] = {{.undefined = true}},
    [0xFD] = {{.undefined = true}},
    [0xFE] = {{.undefined = true}},
    [0xFF] = {{.undefined = true}},
};

const MicroInstr *instructions_get_uinst(u8 opcode, u8 ustep) {
    assert(ustep < MICRO_INSTRUCTION_SIZE);
    return &instructions[opcode][ustep];
}

bool instructions_is_last_ustep(u8 opcode, u8 ustep) {
    if (ustep >= MICRO_INSTRUCTION_SIZE - 1) return true;
    return instructions[opcode][ustep].end;
}